name: hackathon_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
 
  image_picker_widget: ^2.4.1
  intl: ^0.18.1
  counter: ^0.2.2
  dio: 
  reflectable: ^4.0.5
  flutter_provider_utilities: ^1.0.6
  another_flushbar: ^1.12.30
  path_provider: ^2.1.1
  another_flutter_splash_screen: ^1.1.5
  flutter_svg: ^1.1.0
  touchable: ^1.0.2
  xml: ^6.3.0
  path_drawing: ^1.0.1
  syncfusion_flutter_calendar: ^23.1.38
  flutter_local_notifications: 
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  syncfusion_flutter_pdfviewer: ^23.1.41
  syncfusion_flutter_charts: ^23.1.41
  
 
  
 
   
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sections/Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/sections/Logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/sections/Logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/sections/Logo.png"

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  assets:
    - assets/svg/
    - assets/images/sections/
    - assets/images/icons/
  uses-material-design: true


  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/karla/Karla-Bold.ttf
        - asset: assets/fonts/karla/Karla-ExtraBold.ttf
        - asset: assets/fonts/karla/Karla-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
